export enum RabbitMQ {
  AccessControlQueue = 'access-control',
}

export enum UserMsg {
  CREATE = 'CREATE_USER',
  FIND_ALL = 'FIND_USERS',
  FIND_ONE = 'FIND_ONE_USER',
  UPDATE = 'UPDATE_USER',
  DELETE = 'DELETE_USER',
  VALID_USER = 'VALID_USER',
}

export enum RoleMsg {
  CREATE = 'CREATE_ROLE',
  FIND_ALL = 'FIND_ROLES',
  FIND_ONE = 'FIND_ONE_ROLE',
  UPDATE = 'UPDATE_ROLE',
  DELETE = 'DELETE_ROLE',
  VALID_ROLE = 'VALID_ROLE',
}

export enum PermissionMsg {
  CREATE = 'CREATE_PERMISSION',
  FIND_ALL = 'FIND_PERMISSIONS',
  FIND_ONE = 'FIND_ONE_PERMISSION',
  UPDATE = 'UPDATE_PERMISSION',
  DELETE = 'DELETE_PERMISSION',
  VALID_PERMISSION = 'VALID_PERMISSION',
}

export enum OrganizationMsg {
  CREATE = 'CREATE_ORGANIZATION',
  FIND_ALL = 'FIND_ORGANIZATIONS',
  FIND_ONE = 'FIND_ONE_ORGANIZATION',
  UPDATE = 'UPDATE_ORGANIZATION',
  DELETE = 'DELETE_ORGANIZATION',
  VALID_ORGANIZATION = 'VALID_ORGANIZATION',
}
